### ISSUE TITLE
 support a flag/option for getting input directly from the CLI

### ISSUE THREAD

**Issue by aviadhaham** [orellazri/renderkit#31]
gomplate ref:

```
$ gomplate -i 'the answer is: {{ mul 6 7 }}'
the answer is: 42
```

**Comment by orellazri** [comment]
engines currently only support reading from file paths
so you might need to write the value to a temporary file for the engine to render, and then decide for a filename in the output directory

**Comment by aviadhaham** [comment]
@orellazri, gomplate employs a different approach,

It utilizes an input flag (`-i`) for command line input and a file flag (`-f`) for input files. 
Wouldn't it be more efficient to distinguish between them?
While I concur that minimizing the number of flags is desirable, there are instances where differentiation might be the superior choice.

Reference: https://docs.gomplate.ca/usage/#--file-f---in-i-and---out-o

*Written with AI

**Comment by orellazri** [comment]
@aviadhaham that's not what I meant. I mean that you, as the one working on this issue, will need to write the contents from the `-i` flag into a temporary file so the engine can load it, because currently the engines only work with files.

As for the actual flag name, for now we `-i` is used for the input glob, so you'll need to think of something else for a direct input. I think that this use case is less common than the input glob, so the glob should be the one that uses `-i`, and this once is more "niche" so it can be something else like `--direct-input` etc.

I'll create an issue so we can later on think about refactoring the engines to work with a string or a reader.

**Comment by orellazri** [comment]
Let's try to resolve this first: https://github.com/orellazri/renderkit/issues/47
